#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : motif
Version  : 2.3.7
Release  : 5
URL      : https://sourceforge.net/projects/motif/files/Motif%202.3.7%20Source%20Code/motif-2.3.7.tar.gz
Source0  : https://sourceforge.net/projects/motif/files/Motif%202.3.7%20Source%20Code/motif-2.3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: motif-bin
Requires: motif-lib
Requires: motif-data
Requires: motif-doc
BuildRequires : flex
BuildRequires : freetype-dev
BuildRequires : libXrender-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xbitmaps)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xft)
BuildRequires : pkgconfig(xt)
Patch1: wmluiltok-add-option-to-generate-main.patch

%description
Please see the file COPYING  for important information.
Please see the file RELNOTES for current Release information.

%package bin
Summary: bin components for the motif package.
Group: Binaries
Requires: motif-data

%description bin
bin components for the motif package.


%package data
Summary: data components for the motif package.
Group: Data

%description data
data components for the motif package.


%package dev
Summary: dev components for the motif package.
Group: Development
Requires: motif-lib
Requires: motif-bin
Requires: motif-data
Provides: motif-devel

%description dev
dev components for the motif package.


%package doc
Summary: doc components for the motif package.
Group: Documentation

%description doc
doc components for the motif package.


%package lib
Summary: lib components for the motif package.
Group: Libraries
Requires: motif-data

%description lib
lib components for the motif package.


%prep
%setup -q -n motif-2.3.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507842952
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1507842952
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/X11/bindings/acorn
/usr/lib64/X11/bindings/apollo
/usr/lib64/X11/bindings/dec
/usr/lib64/X11/bindings/dg_AViiON
/usr/lib64/X11/bindings/doubleclick
/usr/lib64/X11/bindings/hal
/usr/lib64/X11/bindings/hitachi
/usr/lib64/X11/bindings/hp
/usr/lib64/X11/bindings/ibm
/usr/lib64/X11/bindings/intergraph
/usr/lib64/X11/bindings/intergraph17
/usr/lib64/X11/bindings/megatek
/usr/lib64/X11/bindings/motorola
/usr/lib64/X11/bindings/ncr_at
/usr/lib64/X11/bindings/ncr_vt
/usr/lib64/X11/bindings/pc
/usr/lib64/X11/bindings/sgi
/usr/lib64/X11/bindings/siemens_9733
/usr/lib64/X11/bindings/siemens_wx200
/usr/lib64/X11/bindings/sni
/usr/lib64/X11/bindings/sni_97801
/usr/lib64/X11/bindings/sony
/usr/lib64/X11/bindings/sun
/usr/lib64/X11/bindings/sun_at
/usr/lib64/X11/bindings/tek
/usr/lib64/X11/bindings/xmbind.alias
/usr/lib64/X11/system.mwmrc

%files bin
%defattr(-,root,root,-)
/usr/bin/mwm
/usr/bin/uil
/usr/bin/xmbind

%files data
%defattr(-,root,root,-)
/usr/share/Xm/ButtonBox/bboxdemo
/usr/share/Xm/ButtonBox/bboxdemo.c
/usr/share/Xm/Color/colordemo
/usr/share/Xm/Color/colordemo.c
/usr/share/Xm/Color/util-c.c
/usr/share/Xm/Column/Column.ad
/usr/share/Xm/Column/column
/usr/share/Xm/Column/column.c
/usr/share/Xm/Exm/app_in_c/exm_in_c
/usr/share/Xm/Exm/simple_app/README
/usr/share/Xm/Exm/simple_app/simpleDemo
/usr/share/Xm/Ext18list/callbacks-c.c
/usr/share/Xm/Ext18list/creation.c
/usr/share/Xm/Ext18list/ext18list
/usr/share/Xm/Ext18list/ext18list.c
/usr/share/Xm/Ext18list/extlist.h
/usr/share/Xm/Ext18list/pixmaps/clown.xbm
/usr/share/Xm/Ext18list/pixmaps/crab.xpm
/usr/share/Xm/Ext18list/pixmaps/eye.xpm
/usr/share/Xm/Ext18list/pixmaps/porsche.xpm
/usr/share/Xm/Ext18list/pixmaps/stopsign.xpm
/usr/share/Xm/Ext18list/util-c.c
/usr/share/Xm/Icon/iconbuttondemo
/usr/share/Xm/Icon/iconbuttondemo.c
/usr/share/Xm/Icon/misc.c
/usr/share/Xm/Icon/small.bm
/usr/share/Xm/Outline/outline
/usr/share/Xm/Outline/outline.c
/usr/share/Xm/Paned2/creation-c.c
/usr/share/Xm/Paned2/paned
/usr/share/Xm/Paned2/paned.c
/usr/share/Xm/Tabstack/bxutils.c
/usr/share/Xm/Tabstack/callbacks.c
/usr/share/Xm/Tabstack/creation.c
/usr/share/Xm/Tabstack/creation.h
/usr/share/Xm/Tabstack/main.c
/usr/share/Xm/Tabstack/tabstack
/usr/share/Xm/Tree/bxutil-c.c
/usr/share/Xm/Tree/tree
/usr/share/Xm/Tree/tree.c
/usr/share/Xm/airport/README
/usr/share/Xm/airport/XmdAirport.ad
/usr/share/Xm/airport/airport
/usr/share/Xm/airport/airport.h
/usr/share/Xm/airport/dragsource.c
/usr/share/Xm/airport/dragsource.h
/usr/share/Xm/airport/dropsite.c
/usr/share/Xm/airport/dropsite.h
/usr/share/Xm/airport/main.c
/usr/share/Xm/airport/main.h
/usr/share/Xm/animate/README
/usr/share/Xm/animate/XmdAnimate.ad
/usr/share/Xm/animate/animate.help
/usr/share/Xm/animate/animate.man
/usr/share/Xm/animate/dog.uid
/usr/share/Xm/animate/dog.uil
/usr/share/Xm/animate/plane.uid
/usr/share/Xm/animate/plane.uil
/usr/share/Xm/animate/superman.uid
/usr/share/Xm/animate/superman.uil
/usr/share/Xm/animate/superman1.xbm
/usr/share/Xm/animate/superman2.xbm
/usr/share/Xm/animate/superman3.xbm
/usr/share/Xm/animate/superman4.xbm
/usr/share/Xm/animate/superman5.xbm
/usr/share/Xm/animate/superman6.xbm
/usr/share/Xm/animate/xmanimate
/usr/share/Xm/animate/xmanimate.c
/usr/share/Xm/animate/xmanimate.man
/usr/share/Xm/animate/xmanimate.uid
/usr/share/Xm/animate/xmanimate.uil
/usr/share/Xm/autopopups/README
/usr/share/Xm/autopopups/autopopups
/usr/share/Xm/autopopups/autopopups.c
/usr/share/Xm/autopopups/autopopups.man
/usr/share/Xm/combo2/Combo.ad
/usr/share/Xm/combo2/combo
/usr/share/Xm/combo2/combo.c
/usr/share/Xm/drag_and_drop/DNDDemo
/usr/share/Xm/drag_and_drop/DNDDemo.c
/usr/share/Xm/drag_and_drop/DNDDemo.man
/usr/share/Xm/drag_and_drop/DNDDraw.c
/usr/share/Xm/drag_and_drop/README
/usr/share/Xm/drag_and_drop/simpledrop
/usr/share/Xm/drag_and_drop/simpledrop.c
/usr/share/Xm/drag_and_drop/simpledrop.man
/usr/share/Xm/draw/README
/usr/share/Xm/draw/XmdDraw.ad
/usr/share/Xm/draw/draw
/usr/share/Xm/draw/draw.c
/usr/share/Xm/draw/draw.help
/usr/share/Xm/draw/draw.man
/usr/share/Xm/earth/README
/usr/share/Xm/earth/earth
/usr/share/Xm/earth/earth.c
/usr/share/Xm/earth/earth.man
/usr/share/Xm/earth/terre.xbm
/usr/share/Xm/filemanager/XmdFilemanager.ad
/usr/share/Xm/filemanager/actions.c
/usr/share/Xm/filemanager/code.xpm
/usr/share/Xm/filemanager/convert.c
/usr/share/Xm/filemanager/dir.xpm
/usr/share/Xm/filemanager/exec.xpm
/usr/share/Xm/filemanager/file.xpm
/usr/share/Xm/filemanager/filemanager
/usr/share/Xm/filemanager/filemanager.c
/usr/share/Xm/filemanager/filemanager.h
/usr/share/Xm/filemanager/filemanager.help
/usr/share/Xm/filemanager/filemanager.man
/usr/share/Xm/filemanager/interface.c
/usr/share/Xm/filemanager/none.xpm
/usr/share/Xm/filemanager/obj.xpm
/usr/share/Xm/filemanager/pix.xpm
/usr/share/Xm/filemanager/readdir.c
/usr/share/Xm/filemanager/s_dir.xpm
/usr/share/Xm/filemanager/s_exec.xpm
/usr/share/Xm/filemanager/s_file.xpm
/usr/share/Xm/filemanager/s_none.xpm
/usr/share/Xm/filemanager/s_pix.xpm
/usr/share/Xm/fileview/English.df
/usr/share/Xm/fileview/English.uid
/usr/share/Xm/fileview/English.uil
/usr/share/Xm/fileview/Fileview.ad
/usr/share/Xm/fileview/French.df
/usr/share/Xm/fileview/French.uid
/usr/share/Xm/fileview/French.uil
/usr/share/Xm/fileview/German.df
/usr/share/Xm/fileview/German.uid
/usr/share/Xm/fileview/German.uil
/usr/share/Xm/fileview/README
/usr/share/Xm/fileview/file.c
/usr/share/Xm/fileview/file.h
/usr/share/Xm/fileview/fileE.h
/usr/share/Xm/fileview/fileview
/usr/share/Xm/fileview/fileview.h
/usr/share/Xm/fileview/main.c
/usr/share/Xm/fileview/main.h
/usr/share/Xm/fileview/mainE.h
/usr/share/Xm/fileview/text.c
/usr/share/Xm/fileview/text.h
/usr/share/Xm/fileview/textE.h
/usr/share/Xm/fontsel/callbacks-c.c
/usr/share/Xm/fontsel/creation-c.c
/usr/share/Xm/fontsel/fontsel
/usr/share/Xm/fontsel/fontsel.c
/usr/share/Xm/fontsel/fontsel.h
/usr/share/Xm/getsubres/README
/usr/share/Xm/getsubres/getsubres
/usr/share/Xm/getsubres/getsubres.c
/usr/share/Xm/getsubres/getsubres.help
/usr/share/Xm/getsubres/getsubres.man
/usr/share/Xm/helloint/README
/usr/share/Xm/helloint/helloint
/usr/share/Xm/helloint/helloint.c
/usr/share/Xm/helloint/helloint.man
/usr/share/Xm/helloint/helloint.uid
/usr/share/Xm/helloint/helloint.uil
/usr/share/Xm/hellomotif/README
/usr/share/Xm/hellomotif/hellomotif
/usr/share/Xm/hellomotif/hellomotif.c
/usr/share/Xm/hellomotif/hellomotif.uid
/usr/share/Xm/hellomotif/hellomotif.uil
/usr/share/Xm/i18ninput/README
/usr/share/Xm/i18ninput/XmdI18nInput.ad
/usr/share/Xm/i18ninput/i18ninput
/usr/share/Xm/i18ninput/i18ninput.c
/usr/share/Xm/i18ninput/i18ninput.help
/usr/share/Xm/i18ninput/i18ninput.man
/usr/share/Xm/i18ninput/input.c
/usr/share/Xm/panner/README
/usr/share/Xm/panner/panner
/usr/share/Xm/panner/panner.c
/usr/share/Xm/panner/panner.man
/usr/share/Xm/periodic/README
/usr/share/Xm/periodic/XmdPeriodic.ad
/usr/share/Xm/periodic/periodic
/usr/share/Xm/periodic/periodic.c
/usr/share/Xm/periodic/periodic.uid
/usr/share/Xm/periodic/periodic.uil
/usr/share/Xm/periodic/periodic_l.uil
/usr/share/Xm/piano/Inv8_part1.piano
/usr/share/Xm/piano/Inv8_part2.piano
/usr/share/Xm/piano/README
/usr/share/Xm/piano/piano
/usr/share/Xm/piano/piano.c
/usr/share/Xm/piano/piano.images
/usr/share/Xm/piano/piano.man
/usr/share/Xm/pixmaps/clown.xbm
/usr/share/Xm/pixmaps/crab.xpm
/usr/share/Xm/pixmaps/eye.xpm
/usr/share/Xm/pixmaps/porsche.xpm
/usr/share/Xm/pixmaps/stopsign.xpm
/usr/share/Xm/sampler2_0/README
/usr/share/Xm/sampler2_0/XmdSampler2_0.ad
/usr/share/Xm/sampler2_0/bee.xpm
/usr/share/Xm/sampler2_0/bomb.xpm
/usr/share/Xm/sampler2_0/cherry.xpm
/usr/share/Xm/sampler2_0/da.xpm
/usr/share/Xm/sampler2_0/girlface.xpm
/usr/share/Xm/sampler2_0/k7.xpm
/usr/share/Xm/sampler2_0/labir.xpm
/usr/share/Xm/sampler2_0/main.xpm
/usr/share/Xm/sampler2_0/pile.xpm
/usr/share/Xm/sampler2_0/prev.xpm
/usr/share/Xm/sampler2_0/sampler2_0
/usr/share/Xm/sampler2_0/sampler2_0.c
/usr/share/Xm/sampler2_0/sampler2_0.help
/usr/share/Xm/sampler2_0/sampler2_0.man
/usr/share/Xm/sampler2_0/spir.xpm
/usr/share/Xm/sampler2_0/stack.xpm
/usr/share/Xm/sampler2_0/text.xpm
/usr/share/Xm/setDate/README
/usr/share/Xm/setDate/XmdSetDate.ad
/usr/share/Xm/setDate/setDate
/usr/share/Xm/setDate/setDate.c
/usr/share/Xm/setDate/setDate.man
/usr/share/Xm/todo/README
/usr/share/Xm/todo/XmdTodo.ad
/usr/share/Xm/todo/actions.c
/usr/share/Xm/todo/example.todo
/usr/share/Xm/todo/io.c
/usr/share/Xm/todo/page.h
/usr/share/Xm/todo/todo
/usr/share/Xm/todo/todo.c
/usr/share/Xm/todo/todo.help
/usr/share/Xm/todo/todo.man
/usr/share/Xm/tooltips/tooltips
/usr/share/Xm/tooltips/tooltips.c
/usr/share/Xm/wsm/README
/usr/share/Xm/wsm/client_win.c
/usr/share/Xm/wsm/command_ui.c
/usr/share/Xm/wsm/command_ui.h
/usr/share/Xm/wsm/wsm
/usr/share/Xm/wsm/wsm.c
/usr/share/Xm/wsm/wsm.h
/usr/share/Xm/wsm/wsm.man
/usr/share/Xm/wsm/wsmData.c
/usr/share/Xm/wsm/wsmData.h
/usr/share/Xm/wsm/wsmDebug.c
/usr/share/Xm/wsm/wsmDebug.h
/usr/share/Xm/wsm/wsmSend.c
/usr/share/Xm/wsm/wsmSend.h
/usr/share/Xm/wsm/wsmStruct.c
/usr/share/Xm/wsm/wsmStruct.h
/usr/share/Xm/wsm/wsm_cb.c
/usr/share/Xm/wsm/wsm_cb.h
/usr/share/Xm/wsm/wsm_create.c
/usr/share/Xm/wsm/wsm_create.h
/usr/share/Xm/wsm/wsm_ui.h
/usr/share/Xm/wsm/xrmLib.c
/usr/share/Xm/wsm/xrmLib.h
/usr/share/man/manm/exm_in_c.man
/usr/share/man/manm/simpleDemo.man

%files dev
%defattr(-,root,root,-)
/usr/include/Mrm/MrmAppl.h
/usr/include/Mrm/MrmDecls.h
/usr/include/Mrm/MrmPublic.h
/usr/include/Mrm/MrmosI.h
/usr/include/X11/bitmaps/xm_error
/usr/include/X11/bitmaps/xm_hour16
/usr/include/X11/bitmaps/xm_hour16m
/usr/include/X11/bitmaps/xm_hour32
/usr/include/X11/bitmaps/xm_hour32m
/usr/include/X11/bitmaps/xm_information
/usr/include/X11/bitmaps/xm_noenter16
/usr/include/X11/bitmaps/xm_noenter16m
/usr/include/X11/bitmaps/xm_noenter32
/usr/include/X11/bitmaps/xm_noenter32m
/usr/include/X11/bitmaps/xm_question
/usr/include/X11/bitmaps/xm_warning
/usr/include/X11/bitmaps/xm_working
/usr/include/Xm/AccColorT.h
/usr/include/Xm/AccTextT.h
/usr/include/Xm/ActivatableT.h
/usr/include/Xm/ArrowB.h
/usr/include/Xm/ArrowBG.h
/usr/include/Xm/ArrowBGP.h
/usr/include/Xm/ArrowBP.h
/usr/include/Xm/AtomMgr.h
/usr/include/Xm/BaseClassP.h
/usr/include/Xm/BulletinB.h
/usr/include/Xm/BulletinBP.h
/usr/include/Xm/ButtonBox.h
/usr/include/Xm/ButtonBoxP.h
/usr/include/Xm/CacheP.h
/usr/include/Xm/CareVisualT.h
/usr/include/Xm/CascadeB.h
/usr/include/Xm/CascadeBG.h
/usr/include/Xm/CascadeBGP.h
/usr/include/Xm/CascadeBP.h
/usr/include/Xm/ClipWindowP.h
/usr/include/Xm/ColorObjP.h
/usr/include/Xm/ColorP.h
/usr/include/Xm/ColorS.h
/usr/include/Xm/ColorSP.h
/usr/include/Xm/Column.h
/usr/include/Xm/ColumnP.h
/usr/include/Xm/ComboBox.h
/usr/include/Xm/ComboBox2.h
/usr/include/Xm/ComboBox2P.h
/usr/include/Xm/ComboBoxP.h
/usr/include/Xm/Command.h
/usr/include/Xm/CommandP.h
/usr/include/Xm/ContItemT.h
/usr/include/Xm/Container.h
/usr/include/Xm/ContainerP.h
/usr/include/Xm/ContainerT.h
/usr/include/Xm/CutPaste.h
/usr/include/Xm/DataF.h
/usr/include/Xm/DataFP.h
/usr/include/Xm/DataFSelP.h
/usr/include/Xm/DesktopP.h
/usr/include/Xm/DialogS.h
/usr/include/Xm/DialogSEP.h
/usr/include/Xm/DialogSP.h
/usr/include/Xm/DialogSavvyT.h
/usr/include/Xm/Display.h
/usr/include/Xm/DisplayP.h
/usr/include/Xm/DragC.h
/usr/include/Xm/DragCP.h
/usr/include/Xm/DragDrop.h
/usr/include/Xm/DragIcon.h
/usr/include/Xm/DragIconP.h
/usr/include/Xm/DragOverS.h
/usr/include/Xm/DragOverSP.h
/usr/include/Xm/DrawP.h
/usr/include/Xm/DrawUtils.h
/usr/include/Xm/DrawingA.h
/usr/include/Xm/DrawingAP.h
/usr/include/Xm/DrawnB.h
/usr/include/Xm/DrawnBP.h
/usr/include/Xm/DropDown.h
/usr/include/Xm/DropDownP.h
/usr/include/Xm/DropSMgr.h
/usr/include/Xm/DropSMgrP.h
/usr/include/Xm/DropTrans.h
/usr/include/Xm/DropTransP.h
/usr/include/Xm/Ext.h
/usr/include/Xm/Ext18List.h
/usr/include/Xm/Ext18ListP.h
/usr/include/Xm/ExtObjectP.h
/usr/include/Xm/ExtP.h
/usr/include/Xm/FileSB.h
/usr/include/Xm/FileSBP.h
/usr/include/Xm/FontS.h
/usr/include/Xm/FontSP.h
/usr/include/Xm/Form.h
/usr/include/Xm/FormP.h
/usr/include/Xm/Frame.h
/usr/include/Xm/FrameP.h
/usr/include/Xm/Gadget.h
/usr/include/Xm/GadgetP.h
/usr/include/Xm/GrabShell.h
/usr/include/Xm/GrabShellP.h
/usr/include/Xm/Hierarchy.h
/usr/include/Xm/HierarchyP.h
/usr/include/Xm/IconBox.h
/usr/include/Xm/IconBoxP.h
/usr/include/Xm/IconButton.h
/usr/include/Xm/IconButtonP.h
/usr/include/Xm/IconFile.h
/usr/include/Xm/IconFileP.h
/usr/include/Xm/IconG.h
/usr/include/Xm/IconGP.h
/usr/include/Xm/IconH.h
/usr/include/Xm/IconHP.h
/usr/include/Xm/JoinSideT.h
/usr/include/Xm/Label.h
/usr/include/Xm/LabelG.h
/usr/include/Xm/LabelGP.h
/usr/include/Xm/LabelP.h
/usr/include/Xm/LayoutT.h
/usr/include/Xm/List.h
/usr/include/Xm/ListP.h
/usr/include/Xm/MainW.h
/usr/include/Xm/MainWP.h
/usr/include/Xm/Manager.h
/usr/include/Xm/ManagerP.h
/usr/include/Xm/MenuProcP.h
/usr/include/Xm/MenuShell.h
/usr/include/Xm/MenuShellP.h
/usr/include/Xm/MenuStateP.h
/usr/include/Xm/MenuT.h
/usr/include/Xm/MenuUtilP.h
/usr/include/Xm/MessageB.h
/usr/include/Xm/MessageBP.h
/usr/include/Xm/MultiList.h
/usr/include/Xm/MultiListP.h
/usr/include/Xm/MwmUtil.h
/usr/include/Xm/NavigatorT.h
/usr/include/Xm/Notebook.h
/usr/include/Xm/NotebookP.h
/usr/include/Xm/Outline.h
/usr/include/Xm/OutlineP.h
/usr/include/Xm/Paned.h
/usr/include/Xm/PanedP.h
/usr/include/Xm/PanedW.h
/usr/include/Xm/PanedWP.h
/usr/include/Xm/Picture.h
/usr/include/Xm/PictureP.h
/usr/include/Xm/PointInT.h
/usr/include/Xm/Primitive.h
/usr/include/Xm/PrimitiveP.h
/usr/include/Xm/Print.h
/usr/include/Xm/PrintSP.h
/usr/include/Xm/Protocols.h
/usr/include/Xm/ProtocolsP.h
/usr/include/Xm/PushB.h
/usr/include/Xm/PushBG.h
/usr/include/Xm/PushBGP.h
/usr/include/Xm/PushBP.h
/usr/include/Xm/RCLayoutP.h
/usr/include/Xm/RCMenuP.h
/usr/include/Xm/RepType.h
/usr/include/Xm/RowColumn.h
/usr/include/Xm/RowColumnP.h
/usr/include/Xm/SSpinB.h
/usr/include/Xm/SSpinBP.h
/usr/include/Xm/SashP.h
/usr/include/Xm/Scale.h
/usr/include/Xm/ScaleP.h
/usr/include/Xm/Screen.h
/usr/include/Xm/ScreenP.h
/usr/include/Xm/ScrollBar.h
/usr/include/Xm/ScrollBarP.h
/usr/include/Xm/ScrollFrameT.h
/usr/include/Xm/ScrolledW.h
/usr/include/Xm/ScrolledWP.h
/usr/include/Xm/SelectioB.h
/usr/include/Xm/SelectioBP.h
/usr/include/Xm/SeparatoG.h
/usr/include/Xm/SeparatoGP.h
/usr/include/Xm/Separator.h
/usr/include/Xm/SeparatorP.h
/usr/include/Xm/ShellEP.h
/usr/include/Xm/SlideC.h
/usr/include/Xm/SlideCP.h
/usr/include/Xm/SpecRenderT.h
/usr/include/Xm/SpinB.h
/usr/include/Xm/SpinBP.h
/usr/include/Xm/TabBox.h
/usr/include/Xm/TabBoxP.h
/usr/include/Xm/TabList.h
/usr/include/Xm/TabStack.h
/usr/include/Xm/TabStackP.h
/usr/include/Xm/TakesDefT.h
/usr/include/Xm/TearOffBP.h
/usr/include/Xm/TearOffP.h
/usr/include/Xm/Text.h
/usr/include/Xm/TextF.h
/usr/include/Xm/TextFP.h
/usr/include/Xm/TextFSelP.h
/usr/include/Xm/TextInP.h
/usr/include/Xm/TextOutP.h
/usr/include/Xm/TextP.h
/usr/include/Xm/TextSelP.h
/usr/include/Xm/TextStrSoP.h
/usr/include/Xm/ToggleB.h
/usr/include/Xm/ToggleBG.h
/usr/include/Xm/ToggleBGP.h
/usr/include/Xm/ToggleBP.h
/usr/include/Xm/ToolTipCT.h
/usr/include/Xm/ToolTipT.h
/usr/include/Xm/TraitP.h
/usr/include/Xm/Transfer.h
/usr/include/Xm/TransferP.h
/usr/include/Xm/TransferT.h
/usr/include/Xm/TransltnsP.h
/usr/include/Xm/TravConT.h
/usr/include/Xm/Tree.h
/usr/include/Xm/TreeP.h
/usr/include/Xm/TxtPropCv.h
/usr/include/Xm/UnhighlightT.h
/usr/include/Xm/UnitTypeT.h
/usr/include/Xm/VaSimpleP.h
/usr/include/Xm/VendorS.h
/usr/include/Xm/VendorSEP.h
/usr/include/Xm/VendorSP.h
/usr/include/Xm/VirtKeys.h
/usr/include/Xm/VirtKeysP.h
/usr/include/Xm/Xm.h
/usr/include/Xm/XmAll.h
/usr/include/Xm/XmIm.h
/usr/include/Xm/XmP.h
/usr/include/Xm/XmStrDefs.h
/usr/include/Xm/XmStrDefs22.h
/usr/include/Xm/XmStrDefs23.h
/usr/include/Xm/Xmfuncs.h
/usr/include/Xm/XmosP.h
/usr/include/Xm/Xmos_r.h
/usr/include/Xm/Xmpoll.h
/usr/include/Xm/XpmP.h
/usr/include/Xm/xmlist.h
/usr/include/uil/Uil.h
/usr/include/uil/UilDBDef.h
/usr/include/uil/UilDef.h
/usr/include/uil/UilSymDef.h
/usr/include/uil/UilSymGl.h
/usr/include/uil/XmAppl.uil
/usr/lib64/libMrm.so
/usr/lib64/libUil.so
/usr/lib64/libXm.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man4/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libMrm.so.4
/usr/lib64/libMrm.so.4.0.4
/usr/lib64/libUil.so.4
/usr/lib64/libUil.so.4.0.4
/usr/lib64/libXm.so.4
/usr/lib64/libXm.so.4.0.4
